# Generated by Django 4.2 on 2023-04-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='county',
            field=models.CharField(choices=[('uasin_gishu', 'Uasin Gishu'), ('samburu', 'Samburu'), ('meru', 'Meru'), ('kajiado', 'Kajiado'), ('embu', 'Embu')], max_length=256),
        ),
    ]
