# Generated by Django 4.2.1 on 2023-06-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_rename_status_datamodel_completed_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodel',
            name='task_id',
        ),
    ]
