# Generated by Django 4.2 on 2023-04-27 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_alter_user_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_completed', to=settings.AUTH_USER_MODEL),
        ),
    ]
