# Generated by Django 4.2.1 on 2023-06-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_remove_datamodel_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='completed_status',
            field=models.CharField(choices=[('open', 'Open'), ('Pending', 'pending'), ('Inprogress', 'inprogress'), ('Complete', 'complete'), ('Inreview', 'inreview'), ('Accepted', 'accepted'), ('Rejected', 'rejected'), ('Blocked', 'blocked'), ('Closed', 'closed')], max_length=100),
        ),
    ]
