# Generated by Django 4.2.1 on 2023-06-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_alter_datamodel_completed_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamodel',
            old_name='completed_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(max_length=50),
        ),
    ]
