# Generated by Django 4.2 on 2023-05-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0010_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='title',
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('pending', 'Pending'), ('inprogress', 'Inprogress'), ('complete', 'Complete'), ('inreview', 'InReview'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
