# Generated by Django 4.2 on 2023-05-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0011_remove_subtask_title_alter_task_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('inprogress', 'Inprogress'), ('complete', 'Complete'), ('inreview', 'InReview'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('blocked', 'Blocked'), ('closed', 'Closed')], max_length=100),
        ),
    ]
