# Generated by Django 4.2 on 2023-05-10 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0012_alter_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
