# Generated by Django 4.2 on 2023-05-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0013_alter_subtask_assigned_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='name',
            new_name='task_name',
        ),
    ]
